# Local environment
local.BASE_URI = https://restful-booker.herokuapp.com
local.USERNAME = admin
local.PASSWORD = password123

# Dev environment
dev.BASE_URI = https://restful-booker.herokuapp.com
dev.USERNAME = admin
dev.PASSWORD = password123
